title: "MaGoPaGi"
email: rifkichaplin@gmail.com
timezone: UTC +7
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/Magopagi-M-only-low-res.png'
favicon: 'assets/images/favicon.ico'
author: magopagi
paginate: 30
disqus: 'MaGoPaGi'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-GLWS9TCHC0

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."
  magopagi:
    name: Magopagi
    display_name: magopagi
    avatar: 'assets/images/Magopagi-M-only-low-res'
    instagram: https://www.instagram.com/mago.pagi
    web: https://magopagi.com
    description: "Pedasnya Bikin Nagih, Gurihnya Bikin Balik!"

# Social
social:
  instagram: https://www.instagram.com/mago.pagi
  facebook: https://www.facebook.com/magopagi
  twitter: https://www.instagram.com/mago.pagi

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives